ead:
  service-registry:
    username: serviceregistry
    password: ead123sr

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.service-registry.username}:${ead.service-registry.password}@appserviceregistry:8761/eureka'