ead:
  service-registry:
    username: serviceregistry
    password: ead123sr
  auth:
    jwt-secret: 4u7x!z%C*F-JaNdRgUkXp2s5v8y/B?D(G+KbPeShVmYq3t6w9z$C&F)H@McQfTjW
    jwt-expiration-ms: 14400000

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.service-registry.username}:${ead.service-registry.password}@appserviceregistry:8761/eureka'

