server:
  port: 8086
  servlet:
    context-path: '/ead-payment/'

spring:
  datasource:
    url:  jdbc:postgresql://dbnotification/ead-payment
    username: ead-payment
    password: ead-payment
  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  output:
    ansi:
      enabled: Always
  application:
    name: ead-notification-service
  rabbitmq:
    addresses: amqps://ejafoygf:enS1512dvovFVFOZ0xEok7F7FjDyeOv1@stingray.rmq.cloudamqp.com/ejafoygf

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  broker:
    exchange:
      user-event-exchange: ead.userevent
    queue:
      user-event-queue:
        name: ead.userevent.ms.payment

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

eureka:
  instance:
    hostname: apppayment
