server:
  port: 8084
  servlet:
    context-path: '/ead-notification/'

spring:
  datasource:
    url:  jdbc:postgresql://dbnotification/ead-notification
    username: notification
    password: notification
  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  output:
    ansi:
      enabled: Always
  application:
    name: ead-notification-service
  rabbitmq:
    addresses: amqps://tdtsoinu:7y8afdBR8yRPKnIOq1qqfC3TxWGd7f16@whale.rmq.cloudamqp.com/tdtsoinu

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  broker:
    exchange:
      notification-command-exchange: ead.notificationcommand
    queue:
      notification-command-queue:
        name: ead.notificationcommand.ms.notification
    key:
      notification-command-key: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

eureka:
  instance:
    hostname: appnotification
