server:
  port: 8086
  servlet:
    context-path: '/ead-payment/'

spring:
  datasource:
    url:  jdbc:postgresql://dbpayment/ead-payment
    username: ead-payment
    password: ead-payment
  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  output:
    ansi:
      enabled: Always
  application:
    name: ead-notification-service
  rabbitmq:
    addresses: amqps://ejafoygf:enS1512dvovFVFOZ0xEok7F7FjDyeOv1@stingray.rmq.cloudamqp.com/ejafoygf

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  broker:
    exchange:
      user-event-exchange: 
        name: ead.userevent
      payment-command-exchange: 
        name: ead.paymentcommand
    queue:
      user-event-queue:
        name: ead.userevent.ms.payment
      payment-command-exchange: 
        name: ead.paymentcommand.ms.payment
    key:
      payment-command-key: ms.payment
  stripe:
    secret-key: '{cipher}06247fb941d82ac612a85dba4acb09f9094cdfe3b368bfb5693178f3162984ef76e6127cac8f016c5c33f504383e0a062ae745187cf2fcb79b7338dede0d21871f676cbf13e4dffcc74bf426cd2b30f41dd5b51bbb3c00a86e472c63e95ebd180636679fe6d7ffc005948c59983e212eea6c05a5f1ccec213fb2b3fdddacfc8d'

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

eureka:
  instance:
    hostname: apppayment
