server:
  port: 8084
  servlet:
    context-path: '/ead-notification/'

spring:
  datasource:
    url:  jdbc:postgresql://dbnotification/ead-notification
    username: notification
    password: notification
  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  output:
    ansi:
      enabled: Always
  application:
    name: ead-notification-service
  rabbitmq:
    addresses: amqps://ejafoygf:enS1512dvovFVFOZ0xEok7F7FjDyeOv1@stingray.rmq.cloudamqp.com/ejafoygf

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

eureka:
  instance:
    hostname: appnotification
