server:
  port: 8082
  servlet:
    context-path: '/ead-course'

spring:
  datasource:
    url: jdbc:postgresql://dbcourse/ead-course
    username: ead-course
    password: ead-course

  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        lob:
        non-contextual-creation: true
    properties:
      hibernate:
        show-sql: true
  output:
    ansi:
      enabled: Always

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  application:
    name: ead-course-service

  rabbitmq:
    addresses: amqps://pjnrphkd:FXyA-iEgqCFZPL3LX5XykQ7HVfM5RF4F@stingray.rmq.cloudamqp.com/pjnrphkd

logging:
  level:
    com.ead:  TRACE
    root: INFO
    org.springframework.web:  DEBUG
    org.hibernate:  INFO

ead:
  api:
    url:
      auth-user: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      user-event-exchange: ead.userevent
      notification-command-exchange: ead.notificationcommand
    queue:
      name: ead.userevent.ms.course
    key:
      notification-command-key: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

eureka:
  instance:
    hostname: appcourse